version: "3.9"
services:
  app:
    container_name: app
    # image: ./Dockerfile
    restart: always
    build: .
    ports:
      - "5000:3000"
    depends_on:
      - elasticsearch
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      # - xpack.security.enabled=false
      # - xpack.security.transport.ssl.enabled=false
      # - xpack.security.http.ssl.enabled=false
      # - xpack.security.enrollment.enabled=false
      # - TAKE_FILE_OWNERSHIP=true
      # - xpack.security.autoconfiguration.enabled=false
    ports:
      - '9300:9300'
      - '9200:9200'
    ulimits:
      memlock:
        hard: -1
        soft: -1